name: Build liboqs with Emscripten

on: [push, pull_request]  # Runs on every push and PR

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake ninja-build python3 python3-pip

    - name: Install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        echo "source $(pwd)/emsdk_env.sh" >> $GITHUB_ENV
        cd ..

    - name: Build liboqs with Emscripten
      run: |
        source emsdk/emsdk_env.sh  # Load Emscripten environment
        mkdir build
        cd build
        emcmake cmake .. -GNinja -DOQS_BUILD_ONLY_LIB=ON
        ninja
